import Footer from "../../layouts/Footer/Footer";
import Heading from "../../layouts/Heading";
import Landing from "./Landing";

export default function Shop() {
  return (
    <div>
      <Heading>
        <div className="container mx-auto lg:px-10 text-center">
          <Landing />
        </div>
      </Heading>
      <div className="container mx-auto lg:px-10 text-center">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex dolores
        sequi veniam fuga saepe consequuntur accusantium eos ipsa autem tempora
        velit natus, dolorum minima aperiam officiis quisquam unde beatae. Enim.
      </div>
      <Footer></Footer>
    </div>
  );
}
